### PR TITLE
Typo on #21

### PR DESCRIPTION
**Pull request by kant**

### CODE REVIEW

**Comment by DanRathbun** [comment]
The indicated typo is **not** in the issue #21.

It is in the README.md file, **and** I believe also in the issue post template.
(I've actually noticed several misspelled words in the issue template.)

**Comment by thomthom** [comment]
Thank you for the PR with the typo fix.

**Comment by DanRathbun** [comment]
@thomthom, Is there anyway to disconnect this README issue with the still open Issue 21 ? (Which this had noting to do with.)

**Comment by thomthom** [comment]
I'm not sure what you mean by "disconnect"?

**Comment by DanRathbun** [comment]
Well look at Issue 21. It has a "link" ...

> kant added a commit to kant/api-issue-tracker that referenced this issue on Jun 9, 2018

Apparently his lack of knowing that the pound sign causes links on GitHub has created a link between non-related issues.

**Perhaps start by editing this Issue Title ?**

**Comment by thomthom** [comment]
Those links are managed by GitHub, I don't know of any way to curate them.

Not seeing what the problem is though...?

**Comment by DanRathbun** [comment]
Well I suggested editing the issue title to e correct instead of incorrect. (Ie, removing the "# 21" replacing with "README file, line 21").

Then see if GitHub corrects / removes the link.

(The problem is the link is bogus as this issue had nothing to do with Issue 21.)

**Pull request merged**
